services:
  lilith:
    image: ubuntu
    volumes:
      - ./launcher/:/lilith/
      - ./config/LilithLauncher/:/root/LilithLauncher/
      - ./config/lilith/:/root/lilith/
      - ./ssl/:/etc/ssl
    tty: true
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
