version: "3"
services:
  lilith:
    image: ubuntu
    volumes:
      - ./launcher/:/lilith/
      - ./config/:/root/
      - ./ssl/:/etc/ssl
    tty: true
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
